name: Deploy to Tilt Staging
on:
  push:
    branches: staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "13.13.0"

      - name: Building assets
        run: |
          cd resources
          npm install
          ./node_modules/.bin/gulp

      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3.1.1
        with:
          # Deploy vars
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.PRODUCTION_WPE_SSHG_KEY_PRIVATE }}
          PHP_LINT: false
          CACHE_CLEAR: TRUE

          # GITHUB file location
          TPO_SRC_PATH: "public/wp-content/themes/"

          # WPEngine server location
          TPO_PATH: "wp-content/themes/"

          # Branches & Environments
          STG_BRANCH: staging
          STG_ENV: wearetiltstg
