name: Sync environments

on:
  workflow_run:
    workflows: ["Deploy to Production"]
    types:
      - completed

jobs:
  merge-production-into-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Merge Production into Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge staging -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: staging
          target_branch: staging
          github_token: ${{ github.token }}

      - name: Merge master -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: staging
          github_token: ${{ github.token }}

  merge-production-into-testing:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Merge Production into Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge testing -> testing
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: testing
          target_branch: testing
          github_token: ${{ github.token }}

      - name: Merge master -> testing
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: testing
          github_token: ${{ github.token }}
